# Dependencies
markdown:         redcarpet
pygments:         false

# Permalinks
permalink:        pretty

# Setup
title:            boxmein
tagline:          'here be boxmeins'
description:      'I blog sometimes. Other times I do not.'
url:              http://boxmein.github.io

author:
  name:           'boxmein'
  url:            https://github.com/boxmein

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde